const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOFBRa3JoZ05laXFtem9LTzNDS1RQZEFaczJrOWhzc3Y0am1Yd1Q5Z0gxZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRFhSNmVwSmFMMnpVb051SGR5cXJ2NDlhanJYSnl1ekFNbTFsNFhrSEZRND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZUDhhc2c4azYwbnVmSXB6cEQ5T0VUYjZrVTJiZE9nTmtJSlZWUVlqd1ZRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnZzBUdllsYXhLL2J4WkdwS0ZPZFpLVU80c1dBbUZsOERuclRiR3lxVVd3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9OdElhaml1OVhOUVdJTnJUL0tQN1M3MUNNVVBQeWZMOFhqYTYyYzFUSEk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9kd21iVXU2ZUxDQlpOR21EOWVIbVF1M2V2eGNhd0k3SXl0YTRHSTFKUnM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUlva21rY25NRGRLWU1xQmU5TUZoS0l1SnRSd0NnTURPVEJ2YXNPMm9VMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieFl3WmEyQnlZazJrMFJzNmFDdnFwTUVjZmZabTIwZHZHd0tJUmdSTGxnOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVaR3pzTy8vODJsT2d0QTd6TXVMUjhhdEJrQjcvOGhSUUdqWTVXTk1Bb1NaMXNEKzBTTS84akhGbUd0alNaNGlEZXZaYklhVHc3RkpOaTkzODdMekNnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjA1LCJhZHZTZWNyZXRLZXkiOiI2NDFlYzltd1ZBb2VLSnJmNXNVZWRRV0FlYUwwVGtvZ2YrbEJaUXNTYUhZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjQ5MTUyMDgzNzg2NTFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUM2NjMwQjhGMjBEQjU1OTZBMEE1RDEzOENBQkI5NEEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2MTM3NDc0M31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiR0o2UEdhM29TWHFEcmJLTVl0NmJWQSIsInBob25lSWQiOiJkNzk4ZGY5Yy00MDUxLTQzY2UtODNlYy1mY2UxOTM2MTY4N2MiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYm9waUpabDJQellRLzhDR0pSSGRNNWRFQ3E4PSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpHd3B2Y29zcUd6dWRpU1Q2MUt4bXhZSFNvMD0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJNUk1BTFZJTiIsIm1lIjp7ImlkIjoiNDkxNTIwODM3ODY1MTo0QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjEzMDQ4MTExNDMxNjkyOjRAbGlkIiwibmFtZSI6ImxlbyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTjdKMXN3Q0VJYms4Y2NHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiOWFxVkR0Q2Ryd3J0Nlk3dFNNb0tDbGxNUzhIVEFxQm5laEN5MGY1TTAyYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoic1UxVWhFVCswalV5N1lRM2c2Yy9aVFhaNi9WWlV5eFBzV3pFRFZhUXA4WVZLMDRuN0NEQWhvWlRoMmV3WkcrOTJucHJHaFF1Lyt5RS8zdm9zNXpyQWc9PSIsImRldmljZVNpZ25hdHVyZSI6Ijlad1JIOHU2eXZldlVvYlBhL1I3U0lLVnV0Zm9BbDZSN1ZTWDRzYVpSaDZjRVVTdWZySUFVamwwUElDcGpmQ09XQkxpSzE0U0Z2Y1gzaUxDWEtyckJBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiNDkxNTIwODM3ODY1MTo0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmZXcWxRN1FuYThLN2VtTzdVaktDZ3BaVEV2QjB3S2daM29Rc3RIK1ROTm4ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBTUlDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc2MTM3NDczOSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFLNmIifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
